---
# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
- include: os_definition.yml

- name: RedHat subscriptions
  redhat_subscription:
    username: "{{ rhel_subscription_user }}"
    password: "{{ rhel_subscription_pass }}"
    force_register: no

- name: Retrieve the OpenShift Pool ID
  command: subscription-manager list --available --matches="{{ rhel_subscription_pool }}" --pool-only
  register: openshift_pool_id
  changed_when: False

- name: Determine if OpenShift Pool Already Attached
  command: subscription-manager list --consumed --matches="{{ rhel_subscription_pool }}" --pool-only
  register: openshift_pool_attached
  changed_when: False
  when: openshift_pool_id.stdout == ''

- fail:
    msg: "Unable to find pool matching {{ rhel_subscription_pool }} in available or consumed pools"
  when: openshift_pool_id.stdout == '' and openshift_pool_attached is defined and openshift_pool_attached.stdout == ''

- name: Attach to OpenShift Pool
  command: subscription-manager subscribe --pool {{ openshift_pool_id.stdout_lines[0] }}
  when: openshift_pool_id.stdout != ''

- name: Clean all repositories
  command: subscription-manager repos --disable=*

- name: Clean all repositories
  file: path=/etc/yum.repos.d state=absent

- file: path=/etc/yum.repos.d state=directory

- name: enable the repositories
  command: subscription-manager repos --enable={{ item }}
  with_items:
    - rhel-7-server-rpms
    - rhel-7-server-extras-rpms
    - rhel-7-server-ose-3.9-rpms
    - rhel-7-fast-datapath-rpms
    - rhel-7-server-ansible-2.4-rpms
  when: os_version != 'atomic'
