---
# Copyright (c) 2017 Intel Corporation 
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
- include: os_definition.yml
- name: Add local DNS
  lineinfile:
    dest: /etc/resolv.conf
    state: present
    line: "nameserver 172.30.4.12"
- name: install packagges 
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
     - wget
     - git
     - net-tools
     - bind-utils
     - yum-utils
     - iptables-services
     - bridge-utils
     - bash-completion
     - kexec-tools
     - sos
     - psacct
  when: os_version != 'atomic'
#- name: yum update
#  yum:
#    name: '*'
#    state: latest
#  when: os_version != 'atomic'
- name: atomic-openshift-utils
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - atomic
    - atomic-openshift-utils
    - atomic-openshift-excluder
    - atomic-openshift-docker-excluder
    - docker-1.13.1
    - python-docker-py
  when: os_version != 'atomic'
- name: Workaround for docker 1.13
  lineinfile:
    dest: /etc/yum.conf
    state: present
    line: 'exclude=docker*1.13*'     
- name: Enable insecure registry 
  lineinfile:
    dest: /etc/sysconfig/docker
    state: present
    line: "OPTIONS=' --selinux-enabled --insecure-registry {{ openshift_master_portal_net }}'"
- name: Start and Enable docker
  systemd:
    name: docker
    state: restarted
    enabled: yes
    daemon-reload: yes
